### Explore data with NumPy and Pandas

In [1]:
data = [50,50,47,97,49,3,53,42,26,74,82,62,37,15,70,27,36,35,48,52,63,64]
print(data)

[50, 50, 47, 97, 49, 3, 53, 42, 26, 74, 82, 62, 37, 15, 70, 27, 36, 35, 48, 52, 63, 64]

In [2]:
import numpy as np

grades = np.array(data)
print(grades)

[50 50 47 97 49  3 53 42 26 74 82 62 37 15 70 27 36 35 48 52 63 64]

In [3]:
print (type(data),'x 2:', data * 2)
print('---')
print (type(grades),'x 2:', grades * 2)

<class 'list'> x 2: [50, 50, 47, 97, 49, 3, 53, 42, 26, 74, 82, 62, 37, 15, 70, 27, 36, 35, 48, 52, 63, 64, 50, 50, 47, 97, 49, 3, 53, 42, 26, 74, 82, 62, 37, 15, 70, 27, 36, 35, 48, 52, 63, 64]
---
<class 'numpy.ndarray'> x 2: [100 100  94 194  98   6 106  84  52 148 164 124  74  30 140  54  72  70
  96 104 126 128]

In [4]:
grades.shape #dimensions

(22,)

In [5]:
grades[0] #accessing first element

50

In [6]:
grades.mean()

49.18181818181818

In [7]:
# Define an array of study hours
study_hours = [10.0,11.5,9.0,16.0,9.25,1.0,11.5,9.0,8.5,14.5,15.5,
               13.75,9.0,8.0,15.5,8.0,9.0,6.0,10.0,12.0,12.5,12.0]

# Create a 2D array (an array of arrays)
student_data = np.array([study_hours, grades])

# display the array
student_data

array([[10.  , 11.5 ,  9.  , 16.  ,  9.25,  1.  , 11.5 ,  9.  ,  8.5 ,
        14.5 , 15.5 , 13.75,  9.  ,  8.  , 15.5 ,  8.  ,  9.  ,  6.  ,
        10.  , 12.  , 12.5 , 12.  ],
       [50.  , 50.  , 47.  , 97.  , 49.  ,  3.  , 53.  , 42.  , 26.  ,
        74.  , 82.  , 62.  , 37.  , 15.  , 70.  , 27.  , 36.  , 35.  ,
        48.  , 52.  , 63.  , 64.  ]])

In [8]:
student_data.shape

(2, 22)

In [9]:
# Show the first element of the first element
student_data[0][0]

10.0

In [10]:
# Get the mean value of each sub-array
avg_study = student_data[0].mean()
avg_grade = student_data[1].mean()

print('Average study hours: {:.2f}\nAverage grade: {:.2f}'.format(avg_study, avg_grade))

Average study hours: 10.52
Average grade: 49.18

In [11]:
import pandas as pd

df_students = pd.DataFrame({'Name': ['Dan', 'Joann', 'Pedro', 'Rosie', 'Ethan', 'Vicky', 'Frederic', 'Jimmie', 
                                     'Rhonda', 'Giovanni', 'Francesca', 'Rajab', 'Naiyana', 'Kian', 'Jenny',
                                     'Jakeem','Helena','Ismat','Anila','Skye','Daniel','Aisha'],
                            'StudyHours':student_data[0],
                            'Grade':student_data[1]})

df_students

         Name  StudyHours  Grade
0         Dan       10.00   50.0
1       Joann       11.50   50.0
2       Pedro        9.00   47.0
3       Rosie       16.00   97.0
4       Ethan        9.25   49.0
5       Vicky        1.00    3.0
6    Frederic       11.50   53.0
7      Jimmie        9.00   42.0
8      Rhonda        8.50   26.0
9    Giovanni       14.50   74.0
10  Francesca       15.50   82.0
11      Rajab       13.75   62.0
12    Naiyana        9.00   37.0
13       Kian        8.00   15.0
14      Jenny       15.50   70.0
15     Jakeem        8.00   27.0
16     Helena        9.00   36.0
17      Ismat        6.00   35.0
18      Anila       10.00   48.0
19       Skye       12.00   52.0
20     Daniel       12.50   63.0
21      Aisha       12.00   64.0

In [12]:
# Get the data for index value 5
df_students.loc[5]

Name          Vicky
StudyHours      1.0
Grade           3.0
Name: 5, dtype: object

In [13]:
# Get the rows with index values from 0 to 5
df_students.loc[0:5]

    Name  StudyHours  Grade
0    Dan       10.00   50.0
1  Joann       11.50   50.0
2  Pedro        9.00   47.0
3  Rosie       16.00   97.0
4  Ethan        9.25   49.0
5  Vicky        1.00    3.0

In [14]:
# Get data in the first five rows
df_students.iloc[0:5]

    Name  StudyHours  Grade
0    Dan       10.00   50.0
1  Joann       11.50   50.0
2  Pedro        9.00   47.0
3  Rosie       16.00   97.0
4  Ethan        9.25   49.0

In [15]:
df_students.iloc[0,[1,2]]

StudyHours    10.0
Grade         50.0
Name: 0, dtype: object

In [16]:
df_students.loc[0,'Grade']

50.0

In [17]:
df_students.loc[df_students['Name']=='Aisha']

     Name  StudyHours  Grade
21  Aisha        12.0   64.0

In [18]:
df_students[df_students['Name']=='Aisha']

     Name  StudyHours  Grade
21  Aisha        12.0   64.0

In [19]:
df_students.query('Name=="Aisha"')

     Name  StudyHours  Grade
21  Aisha        12.0   64.0

In [20]:
df_students[df_students.Name == 'Aisha']

     Name  StudyHours  Grade
21  Aisha        12.0   64.0

In [44]:
#!wget C:\Users\pswar\Downloads\study.csv
df_students = pd.read_csv('C://Users//pswar//Downloads//study.csv',delimiter=',',header='infer')
df_students

         Name  StudyHours  Grade
0         Dan       10.00   50.0
1       Joann       11.50   50.0
2       Pedro        9.00   47.0
3       Rosie       16.00   97.0
4       Ethan        9.25   49.0
5       Vicky        1.00    3.0
6    Frederic       11.50   53.0
7      Jimmie        9.00   42.0
8      Rhonda        8.50   26.0
9    Giovanni       14.50   74.0
10  Francesca       15.50   82.0
11      Rajab       13.75   62.0
12    Naiyana        9.00   37.0
13       Kian        8.00   15.0
14      Jenny       15.50   70.0
15     Jakeem        8.00   27.0
16     Helena        9.00   36.0
17      Ismat        6.00   35.0
18      Anila       10.00   48.0
19       Skye       12.00   52.0
20     Daniel       12.50   63.0
21      Aisha       12.00   64.0
22       Bill        8.00    NaN
23        Ted         NaN    NaN

In [45]:
df_students.isnull()

     Name  StudyHours  Grade
0   False       False  False
1   False       False  False
2   False       False  False
3   False       False  False
4   False       False  False
5   False       False  False
6   False       False  False
7   False       False  False
8   False       False  False
9   False       False  False
10  False       False  False
11  False       False  False
12  False       False  False
13  False       False  False
14  False       False  False
15  False       False  False
16  False       False  False
17  False       False  False
18  False       False  False
19  False       False  False
20  False       False  False
21  False       False  False
22  False       False   True
23  False        True   True

In [46]:
df_students.isnull().sum()

Name          0
StudyHours    1
Grade         2
dtype: int64

In [48]:
df_students[df_students.isnull().any(axis=1)]

    Name  StudyHours  Grade
22  Bill         8.0    NaN
23   Ted         NaN    NaN

In [49]:
#replacing null values with mean
df_students.StudyHours = df_students.StudyHours.fillna(df_students.StudyHours.mean())
df_students

         Name  StudyHours  Grade
0         Dan   10.000000   50.0
1       Joann   11.500000   50.0
2       Pedro    9.000000   47.0
3       Rosie   16.000000   97.0
4       Ethan    9.250000   49.0
5       Vicky    1.000000    3.0
6    Frederic   11.500000   53.0
7      Jimmie    9.000000   42.0
8      Rhonda    8.500000   26.0
9    Giovanni   14.500000   74.0
10  Francesca   15.500000   82.0
11      Rajab   13.750000   62.0
12    Naiyana    9.000000   37.0
13       Kian    8.000000   15.0
14      Jenny   15.500000   70.0
15     Jakeem    8.000000   27.0
16     Helena    9.000000   36.0
17      Ismat    6.000000   35.0
18      Anila   10.000000   48.0
19       Skye   12.000000   52.0
20     Daniel   12.500000   63.0
21      Aisha   12.000000   64.0
22       Bill    8.000000    NaN
23        Ted   10.413043    NaN

In [50]:
df_students = df_students.dropna(axis=0, how='any')
df_students

         Name  StudyHours  Grade
0         Dan       10.00   50.0
1       Joann       11.50   50.0
2       Pedro        9.00   47.0
3       Rosie       16.00   97.0
4       Ethan        9.25   49.0
5       Vicky        1.00    3.0
6    Frederic       11.50   53.0
7      Jimmie        9.00   42.0
8      Rhonda        8.50   26.0
9    Giovanni       14.50   74.0
10  Francesca       15.50   82.0
11      Rajab       13.75   62.0
12    Naiyana        9.00   37.0
13       Kian        8.00   15.0
14      Jenny       15.50   70.0
15     Jakeem        8.00   27.0
16     Helena        9.00   36.0
17      Ismat        6.00   35.0
18      Anila       10.00   48.0
19       Skye       12.00   52.0
20     Daniel       12.50   63.0
21      Aisha       12.00   64.0

In [51]:
# Get the mean study hours using to column name as an index
mean_study = df_students['StudyHours'].mean()

# Get the mean grade using the column name as a property (just to make the point!)
mean_grade = df_students.Grade.mean()

# Print the mean study hours and mean grade
print('Average weekly study hours: {:.2f}\nAverage grade: {:.2f}'.format(mean_study, mean_grade))

Average weekly study hours: 10.52
Average grade: 49.18

In [52]:
# Get students who studied for the mean or more hours
df_students[df_students.StudyHours > mean_study]

         Name  StudyHours  Grade
1       Joann       11.50   50.0
3       Rosie       16.00   97.0
6    Frederic       11.50   53.0
9    Giovanni       14.50   74.0
10  Francesca       15.50   82.0
11      Rajab       13.75   62.0
14      Jenny       15.50   70.0
19       Skye       12.00   52.0
20     Daniel       12.50   63.0
21      Aisha       12.00   64.0

In [53]:
# What was their mean grade?
df_students[df_students.StudyHours > mean_study].Grade.mean()

66.7

Let the passing grade is 60

In [54]:
passes = pd.Series(df_students['Grade']>=60)
df_students = pd.concat([df_students, passes.rename('Pass')],axis=1)
df_students

         Name  StudyHours  Grade   Pass
0         Dan       10.00   50.0  False
1       Joann       11.50   50.0  False
2       Pedro        9.00   47.0  False
3       Rosie       16.00   97.0   True
4       Ethan        9.25   49.0  False
5       Vicky        1.00    3.0  False
6    Frederic       11.50   53.0  False
7      Jimmie        9.00   42.0  False
8      Rhonda        8.50   26.0  False
9    Giovanni       14.50   74.0   True
10  Francesca       15.50   82.0   True
11      Rajab       13.75   62.0   True
12    Naiyana        9.00   37.0  False
13       Kian        8.00   15.0  False
14      Jenny       15.50   70.0   True
15     Jakeem        8.00   27.0  False
16     Helena        9.00   36.0  False
17      Ismat        6.00   35.0  False
18      Anila       10.00   48.0  False
19       Skye       12.00   52.0  False
20     Daniel       12.50   63.0   True
21      Aisha       12.00   64.0   True

In [55]:
print(df_students.groupby(df_students.Pass).Name.count())

Pass
False    15
True      7
Name: Name, dtype: int64

In [56]:
#aggregating multiple fields
print(df_students.groupby(df_students.Pass)[['StudyHours','Grade']].mean())

       StudyHours      Grade
Pass
False    8.783333  38.000000
True    14.250000  73.142857

In [57]:
# Create a DataFrame with the data sorted by Grade (descending)
df_students = df_students.sort_values('Grade', ascending=False)

# Show the DataFrame
df_students

         Name  StudyHours  Grade   Pass
3       Rosie       16.00   97.0   True
10  Francesca       15.50   82.0   True
9    Giovanni       14.50   74.0   True
14      Jenny       15.50   70.0   True
21      Aisha       12.00   64.0   True
20     Daniel       12.50   63.0   True
11      Rajab       13.75   62.0   True
6    Frederic       11.50   53.0  False
19       Skye       12.00   52.0  False
1       Joann       11.50   50.0  False
0         Dan       10.00   50.0  False
4       Ethan        9.25   49.0  False
18      Anila       10.00   48.0  False
2       Pedro        9.00   47.0  False
7      Jimmie        9.00   42.0  False
12    Naiyana        9.00   37.0  False
16     Helena        9.00   36.0  False
17      Ismat        6.00   35.0  False
15     Jakeem        8.00   27.0  False
8      Rhonda        8.50   26.0  False
13       Kian        8.00   15.0  False
5       Vicky        1.00    3.0  False